### ISSUE TITLE
Impossible to save Hails endpoint

### ISSUE THREAD

**Issue by supmob1** [openmaraude/APITaxi#211] opened 2015-08-24 19:32 UTC
I tried to change my Hails endpoint into the backoffice portal but it does not save
![2015-08-24 21_29_55-registre des taxis](https://cloud.githubusercontent.com/assets/13950612/9450219/ba724e6a-4aa7-11e5-9d42-c4c98a6c6ceb.png)

Could you please have a look because we need to test our hails endpoint

**Comment by odtvince** [comment] 2015-08-24 20:13
We will have a look asap.
In the mean time, if you can send me your endpoints by e-mail, I can add them right now.

**Comment by odtvince** [comment] 2015-08-24 20:23
In fact, the cause is a cache on our side not properly flushed when you use that form. 
Your new endpoints were already saved. 
I manually flushed the cache, so you should see them now.

**Comment by odtvince** [comment] 2015-08-25 19:28
fixed in #212

**Closed by odtvince** 2015-08-25 19:28 UTC

**Comment by supmob1** [comment] 2015-08-25 22:06
Thks a lot for your fast replay :)
